@startuml
'https://plantuml.com/sequence-diagram

object Rents {
    dateStart
    dateEnd
    idContact
        idBook
}

object Borrow{
}

object Books {
    name
    description
    ISBN

}

Books "1" -- "n" Borrow
Borrow "1" -- "1" Rents


@enduml
